# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/parallels/Desktop/ECE3574/proj3_new/ece3574-sp22-proj3-yichenl61

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/parallels/Desktop/ECE3574/proj3_new/ece3574-sp22-proj3-yichenl61

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/parallels/Desktop/ECE3574/proj3_new/ece3574-sp22-proj3-yichenl61/CMakeFiles /home/parallels/Desktop/ECE3574/proj3_new/ece3574-sp22-proj3-yichenl61/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/parallels/Desktop/ECE3574/proj3_new/ece3574-sp22-proj3-yichenl61/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tidy

# Build rule for target.
tidy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tidy
.PHONY : tidy

# fast build rule for target.
tidy/fast:
	$(MAKE) -f CMakeFiles/tidy.dir/build.make CMakeFiles/tidy.dir/build
.PHONY : tidy/fast

#=============================================================================
# Target rules for targets named test_message

# Build rule for target.
test_message: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_message
.PHONY : test_message

# fast build rule for target.
test_message/fast:
	$(MAKE) -f CMakeFiles/test_message.dir/build.make CMakeFiles/test_message.dir/build
.PHONY : test_message/fast

#=============================================================================
# Target rules for targets named test_gui

# Build rule for target.
test_gui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_gui
.PHONY : test_gui

# fast build rule for target.
test_gui/fast:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/build
.PHONY : test_gui/fast

#=============================================================================
# Target rules for targets named unittests

# Build rule for target.
unittests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittests
.PHONY : unittests

# fast build rule for target.
unittests/fast:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/build
.PHONY : unittests/fast

#=============================================================================
# Target rules for targets named sldraw

# Build rule for target.
sldraw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sldraw
.PHONY : sldraw

# fast build rule for target.
sldraw/fast:
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/build
.PHONY : sldraw/fast

#=============================================================================
# Target rules for targets named coverage

# Build rule for target.
coverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coverage
.PHONY : coverage

# fast build rule for target.
coverage/fast:
	$(MAKE) -f CMakeFiles/coverage.dir/build.make CMakeFiles/coverage.dir/build
.PHONY : coverage/fast

#=============================================================================
# Target rules for targets named slisp

# Build rule for target.
slisp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slisp
.PHONY : slisp

# fast build rule for target.
slisp/fast:
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/build
.PHONY : slisp/fast

#=============================================================================
# Target rules for targets named test_message_autogen

# Build rule for target.
test_message_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_message_autogen
.PHONY : test_message_autogen

# fast build rule for target.
test_message_autogen/fast:
	$(MAKE) -f CMakeFiles/test_message_autogen.dir/build.make CMakeFiles/test_message_autogen.dir/build
.PHONY : test_message_autogen/fast

#=============================================================================
# Target rules for targets named test_gui_autogen

# Build rule for target.
test_gui_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_gui_autogen
.PHONY : test_gui_autogen

# fast build rule for target.
test_gui_autogen/fast:
	$(MAKE) -f CMakeFiles/test_gui_autogen.dir/build.make CMakeFiles/test_gui_autogen.dir/build
.PHONY : test_gui_autogen/fast

#=============================================================================
# Target rules for targets named unittests_autogen

# Build rule for target.
unittests_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittests_autogen
.PHONY : unittests_autogen

# fast build rule for target.
unittests_autogen/fast:
	$(MAKE) -f CMakeFiles/unittests_autogen.dir/build.make CMakeFiles/unittests_autogen.dir/build
.PHONY : unittests_autogen/fast

#=============================================================================
# Target rules for targets named sldraw_autogen

# Build rule for target.
sldraw_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sldraw_autogen
.PHONY : sldraw_autogen

# fast build rule for target.
sldraw_autogen/fast:
	$(MAKE) -f CMakeFiles/sldraw_autogen.dir/build.make CMakeFiles/sldraw_autogen.dir/build
.PHONY : sldraw_autogen/fast

#=============================================================================
# Target rules for targets named slisp_autogen

# Build rule for target.
slisp_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slisp_autogen
.PHONY : slisp_autogen

# fast build rule for target.
slisp_autogen/fast:
	$(MAKE) -f CMakeFiles/slisp_autogen.dir/build.make CMakeFiles/slisp_autogen.dir/build
.PHONY : slisp_autogen/fast

canvas_widget.o: canvas_widget.cpp.o

.PHONY : canvas_widget.o

# target to build an object file
canvas_widget.cpp.o:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/canvas_widget.cpp.o
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/canvas_widget.cpp.o
.PHONY : canvas_widget.cpp.o

canvas_widget.i: canvas_widget.cpp.i

.PHONY : canvas_widget.i

# target to preprocess a source file
canvas_widget.cpp.i:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/canvas_widget.cpp.i
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/canvas_widget.cpp.i
.PHONY : canvas_widget.cpp.i

canvas_widget.s: canvas_widget.cpp.s

.PHONY : canvas_widget.s

# target to generate assembly for a file
canvas_widget.cpp.s:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/canvas_widget.cpp.s
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/canvas_widget.cpp.s
.PHONY : canvas_widget.cpp.s

environment.o: environment.cpp.o

.PHONY : environment.o

# target to build an object file
environment.cpp.o:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/environment.cpp.o
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/environment.cpp.o
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/environment.cpp.o
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/environment.cpp.o
.PHONY : environment.cpp.o

environment.i: environment.cpp.i

.PHONY : environment.i

# target to preprocess a source file
environment.cpp.i:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/environment.cpp.i
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/environment.cpp.i
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/environment.cpp.i
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/environment.cpp.i
.PHONY : environment.cpp.i

environment.s: environment.cpp.s

.PHONY : environment.s

# target to generate assembly for a file
environment.cpp.s:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/environment.cpp.s
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/environment.cpp.s
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/environment.cpp.s
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/environment.cpp.s
.PHONY : environment.cpp.s

expression.o: expression.cpp.o

.PHONY : expression.o

# target to build an object file
expression.cpp.o:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/expression.cpp.o
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/expression.cpp.o
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/expression.cpp.o
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/expression.cpp.o
.PHONY : expression.cpp.o

expression.i: expression.cpp.i

.PHONY : expression.i

# target to preprocess a source file
expression.cpp.i:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/expression.cpp.i
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/expression.cpp.i
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/expression.cpp.i
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/expression.cpp.i
.PHONY : expression.cpp.i

expression.s: expression.cpp.s

.PHONY : expression.s

# target to generate assembly for a file
expression.cpp.s:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/expression.cpp.s
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/expression.cpp.s
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/expression.cpp.s
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/expression.cpp.s
.PHONY : expression.cpp.s

interpreter.o: interpreter.cpp.o

.PHONY : interpreter.o

# target to build an object file
interpreter.cpp.o:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/interpreter.cpp.o
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/interpreter.cpp.o
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/interpreter.cpp.o
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/interpreter.cpp.o
.PHONY : interpreter.cpp.o

interpreter.i: interpreter.cpp.i

.PHONY : interpreter.i

# target to preprocess a source file
interpreter.cpp.i:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/interpreter.cpp.i
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/interpreter.cpp.i
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/interpreter.cpp.i
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/interpreter.cpp.i
.PHONY : interpreter.cpp.i

interpreter.s: interpreter.cpp.s

.PHONY : interpreter.s

# target to generate assembly for a file
interpreter.cpp.s:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/interpreter.cpp.s
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/interpreter.cpp.s
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/interpreter.cpp.s
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/interpreter.cpp.s
.PHONY : interpreter.cpp.s

main_window.o: main_window.cpp.o

.PHONY : main_window.o

# target to build an object file
main_window.cpp.o:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/main_window.cpp.o
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/main_window.cpp.o
.PHONY : main_window.cpp.o

main_window.i: main_window.cpp.i

.PHONY : main_window.i

# target to preprocess a source file
main_window.cpp.i:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/main_window.cpp.i
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/main_window.cpp.i
.PHONY : main_window.cpp.i

main_window.s: main_window.cpp.s

.PHONY : main_window.s

# target to generate assembly for a file
main_window.cpp.s:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/main_window.cpp.s
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/main_window.cpp.s
.PHONY : main_window.cpp.s

message_widget.o: message_widget.cpp.o

.PHONY : message_widget.o

# target to build an object file
message_widget.cpp.o:
	$(MAKE) -f CMakeFiles/test_message.dir/build.make CMakeFiles/test_message.dir/message_widget.cpp.o
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/message_widget.cpp.o
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/message_widget.cpp.o
.PHONY : message_widget.cpp.o

message_widget.i: message_widget.cpp.i

.PHONY : message_widget.i

# target to preprocess a source file
message_widget.cpp.i:
	$(MAKE) -f CMakeFiles/test_message.dir/build.make CMakeFiles/test_message.dir/message_widget.cpp.i
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/message_widget.cpp.i
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/message_widget.cpp.i
.PHONY : message_widget.cpp.i

message_widget.s: message_widget.cpp.s

.PHONY : message_widget.s

# target to generate assembly for a file
message_widget.cpp.s:
	$(MAKE) -f CMakeFiles/test_message.dir/build.make CMakeFiles/test_message.dir/message_widget.cpp.s
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/message_widget.cpp.s
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/message_widget.cpp.s
.PHONY : message_widget.cpp.s

qgraphics_arc_item.o: qgraphics_arc_item.cpp.o

.PHONY : qgraphics_arc_item.o

# target to build an object file
qgraphics_arc_item.cpp.o:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/qgraphics_arc_item.cpp.o
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/qgraphics_arc_item.cpp.o
.PHONY : qgraphics_arc_item.cpp.o

qgraphics_arc_item.i: qgraphics_arc_item.cpp.i

.PHONY : qgraphics_arc_item.i

# target to preprocess a source file
qgraphics_arc_item.cpp.i:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/qgraphics_arc_item.cpp.i
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/qgraphics_arc_item.cpp.i
.PHONY : qgraphics_arc_item.cpp.i

qgraphics_arc_item.s: qgraphics_arc_item.cpp.s

.PHONY : qgraphics_arc_item.s

# target to generate assembly for a file
qgraphics_arc_item.cpp.s:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/qgraphics_arc_item.cpp.s
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/qgraphics_arc_item.cpp.s
.PHONY : qgraphics_arc_item.cpp.s

qt_interpreter.o: qt_interpreter.cpp.o

.PHONY : qt_interpreter.o

# target to build an object file
qt_interpreter.cpp.o:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/qt_interpreter.cpp.o
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/qt_interpreter.cpp.o
.PHONY : qt_interpreter.cpp.o

qt_interpreter.i: qt_interpreter.cpp.i

.PHONY : qt_interpreter.i

# target to preprocess a source file
qt_interpreter.cpp.i:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/qt_interpreter.cpp.i
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/qt_interpreter.cpp.i
.PHONY : qt_interpreter.cpp.i

qt_interpreter.s: qt_interpreter.cpp.s

.PHONY : qt_interpreter.s

# target to generate assembly for a file
qt_interpreter.cpp.s:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/qt_interpreter.cpp.s
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/qt_interpreter.cpp.s
.PHONY : qt_interpreter.cpp.s

repl_widget.o: repl_widget.cpp.o

.PHONY : repl_widget.o

# target to build an object file
repl_widget.cpp.o:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/repl_widget.cpp.o
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/repl_widget.cpp.o
.PHONY : repl_widget.cpp.o

repl_widget.i: repl_widget.cpp.i

.PHONY : repl_widget.i

# target to preprocess a source file
repl_widget.cpp.i:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/repl_widget.cpp.i
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/repl_widget.cpp.i
.PHONY : repl_widget.cpp.i

repl_widget.s: repl_widget.cpp.s

.PHONY : repl_widget.s

# target to generate assembly for a file
repl_widget.cpp.s:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/repl_widget.cpp.s
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/repl_widget.cpp.s
.PHONY : repl_widget.cpp.s

sldraw.o: sldraw.cpp.o

.PHONY : sldraw.o

# target to build an object file
sldraw.cpp.o:
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/sldraw.cpp.o
.PHONY : sldraw.cpp.o

sldraw.i: sldraw.cpp.i

.PHONY : sldraw.i

# target to preprocess a source file
sldraw.cpp.i:
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/sldraw.cpp.i
.PHONY : sldraw.cpp.i

sldraw.s: sldraw.cpp.s

.PHONY : sldraw.s

# target to generate assembly for a file
sldraw.cpp.s:
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/sldraw.cpp.s
.PHONY : sldraw.cpp.s

sldraw_autogen/mocs_compilation.o: sldraw_autogen/mocs_compilation.cpp.o

.PHONY : sldraw_autogen/mocs_compilation.o

# target to build an object file
sldraw_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/sldraw_autogen/mocs_compilation.cpp.o
.PHONY : sldraw_autogen/mocs_compilation.cpp.o

sldraw_autogen/mocs_compilation.i: sldraw_autogen/mocs_compilation.cpp.i

.PHONY : sldraw_autogen/mocs_compilation.i

# target to preprocess a source file
sldraw_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/sldraw_autogen/mocs_compilation.cpp.i
.PHONY : sldraw_autogen/mocs_compilation.cpp.i

sldraw_autogen/mocs_compilation.s: sldraw_autogen/mocs_compilation.cpp.s

.PHONY : sldraw_autogen/mocs_compilation.s

# target to generate assembly for a file
sldraw_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/sldraw_autogen/mocs_compilation.cpp.s
.PHONY : sldraw_autogen/mocs_compilation.cpp.s

slisp.o: slisp.cpp.o

.PHONY : slisp.o

# target to build an object file
slisp.cpp.o:
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/slisp.cpp.o
.PHONY : slisp.cpp.o

slisp.i: slisp.cpp.i

.PHONY : slisp.i

# target to preprocess a source file
slisp.cpp.i:
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/slisp.cpp.i
.PHONY : slisp.cpp.i

slisp.s: slisp.cpp.s

.PHONY : slisp.s

# target to generate assembly for a file
slisp.cpp.s:
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/slisp.cpp.s
.PHONY : slisp.cpp.s

slisp_autogen/mocs_compilation.o: slisp_autogen/mocs_compilation.cpp.o

.PHONY : slisp_autogen/mocs_compilation.o

# target to build an object file
slisp_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/slisp_autogen/mocs_compilation.cpp.o
.PHONY : slisp_autogen/mocs_compilation.cpp.o

slisp_autogen/mocs_compilation.i: slisp_autogen/mocs_compilation.cpp.i

.PHONY : slisp_autogen/mocs_compilation.i

# target to preprocess a source file
slisp_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/slisp_autogen/mocs_compilation.cpp.i
.PHONY : slisp_autogen/mocs_compilation.cpp.i

slisp_autogen/mocs_compilation.s: slisp_autogen/mocs_compilation.cpp.s

.PHONY : slisp_autogen/mocs_compilation.s

# target to generate assembly for a file
slisp_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/slisp_autogen/mocs_compilation.cpp.s
.PHONY : slisp_autogen/mocs_compilation.cpp.s

test_gui.o: test_gui.cpp.o

.PHONY : test_gui.o

# target to build an object file
test_gui.cpp.o:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/test_gui.cpp.o
.PHONY : test_gui.cpp.o

test_gui.i: test_gui.cpp.i

.PHONY : test_gui.i

# target to preprocess a source file
test_gui.cpp.i:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/test_gui.cpp.i
.PHONY : test_gui.cpp.i

test_gui.s: test_gui.cpp.s

.PHONY : test_gui.s

# target to generate assembly for a file
test_gui.cpp.s:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/test_gui.cpp.s
.PHONY : test_gui.cpp.s

test_gui_autogen/mocs_compilation.o: test_gui_autogen/mocs_compilation.cpp.o

.PHONY : test_gui_autogen/mocs_compilation.o

# target to build an object file
test_gui_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/test_gui_autogen/mocs_compilation.cpp.o
.PHONY : test_gui_autogen/mocs_compilation.cpp.o

test_gui_autogen/mocs_compilation.i: test_gui_autogen/mocs_compilation.cpp.i

.PHONY : test_gui_autogen/mocs_compilation.i

# target to preprocess a source file
test_gui_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/test_gui_autogen/mocs_compilation.cpp.i
.PHONY : test_gui_autogen/mocs_compilation.cpp.i

test_gui_autogen/mocs_compilation.s: test_gui_autogen/mocs_compilation.cpp.s

.PHONY : test_gui_autogen/mocs_compilation.s

# target to generate assembly for a file
test_gui_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/test_gui_autogen/mocs_compilation.cpp.s
.PHONY : test_gui_autogen/mocs_compilation.cpp.s

test_interpreter.o: test_interpreter.cpp.o

.PHONY : test_interpreter.o

# target to build an object file
test_interpreter.cpp.o:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/test_interpreter.cpp.o
.PHONY : test_interpreter.cpp.o

test_interpreter.i: test_interpreter.cpp.i

.PHONY : test_interpreter.i

# target to preprocess a source file
test_interpreter.cpp.i:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/test_interpreter.cpp.i
.PHONY : test_interpreter.cpp.i

test_interpreter.s: test_interpreter.cpp.s

.PHONY : test_interpreter.s

# target to generate assembly for a file
test_interpreter.cpp.s:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/test_interpreter.cpp.s
.PHONY : test_interpreter.cpp.s

test_message.o: test_message.cpp.o

.PHONY : test_message.o

# target to build an object file
test_message.cpp.o:
	$(MAKE) -f CMakeFiles/test_message.dir/build.make CMakeFiles/test_message.dir/test_message.cpp.o
.PHONY : test_message.cpp.o

test_message.i: test_message.cpp.i

.PHONY : test_message.i

# target to preprocess a source file
test_message.cpp.i:
	$(MAKE) -f CMakeFiles/test_message.dir/build.make CMakeFiles/test_message.dir/test_message.cpp.i
.PHONY : test_message.cpp.i

test_message.s: test_message.cpp.s

.PHONY : test_message.s

# target to generate assembly for a file
test_message.cpp.s:
	$(MAKE) -f CMakeFiles/test_message.dir/build.make CMakeFiles/test_message.dir/test_message.cpp.s
.PHONY : test_message.cpp.s

test_message_autogen/mocs_compilation.o: test_message_autogen/mocs_compilation.cpp.o

.PHONY : test_message_autogen/mocs_compilation.o

# target to build an object file
test_message_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/test_message.dir/build.make CMakeFiles/test_message.dir/test_message_autogen/mocs_compilation.cpp.o
.PHONY : test_message_autogen/mocs_compilation.cpp.o

test_message_autogen/mocs_compilation.i: test_message_autogen/mocs_compilation.cpp.i

.PHONY : test_message_autogen/mocs_compilation.i

# target to preprocess a source file
test_message_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/test_message.dir/build.make CMakeFiles/test_message.dir/test_message_autogen/mocs_compilation.cpp.i
.PHONY : test_message_autogen/mocs_compilation.cpp.i

test_message_autogen/mocs_compilation.s: test_message_autogen/mocs_compilation.cpp.s

.PHONY : test_message_autogen/mocs_compilation.s

# target to generate assembly for a file
test_message_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/test_message.dir/build.make CMakeFiles/test_message.dir/test_message_autogen/mocs_compilation.cpp.s
.PHONY : test_message_autogen/mocs_compilation.cpp.s

test_tokenize.o: test_tokenize.cpp.o

.PHONY : test_tokenize.o

# target to build an object file
test_tokenize.cpp.o:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/test_tokenize.cpp.o
.PHONY : test_tokenize.cpp.o

test_tokenize.i: test_tokenize.cpp.i

.PHONY : test_tokenize.i

# target to preprocess a source file
test_tokenize.cpp.i:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/test_tokenize.cpp.i
.PHONY : test_tokenize.cpp.i

test_tokenize.s: test_tokenize.cpp.s

.PHONY : test_tokenize.s

# target to generate assembly for a file
test_tokenize.cpp.s:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/test_tokenize.cpp.s
.PHONY : test_tokenize.cpp.s

test_types.o: test_types.cpp.o

.PHONY : test_types.o

# target to build an object file
test_types.cpp.o:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/test_types.cpp.o
.PHONY : test_types.cpp.o

test_types.i: test_types.cpp.i

.PHONY : test_types.i

# target to preprocess a source file
test_types.cpp.i:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/test_types.cpp.i
.PHONY : test_types.cpp.i

test_types.s: test_types.cpp.s

.PHONY : test_types.s

# target to generate assembly for a file
test_types.cpp.s:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/test_types.cpp.s
.PHONY : test_types.cpp.s

tokenize.o: tokenize.cpp.o

.PHONY : tokenize.o

# target to build an object file
tokenize.cpp.o:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/tokenize.cpp.o
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/tokenize.cpp.o
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/tokenize.cpp.o
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/tokenize.cpp.o
.PHONY : tokenize.cpp.o

tokenize.i: tokenize.cpp.i

.PHONY : tokenize.i

# target to preprocess a source file
tokenize.cpp.i:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/tokenize.cpp.i
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/tokenize.cpp.i
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/tokenize.cpp.i
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/tokenize.cpp.i
.PHONY : tokenize.cpp.i

tokenize.s: tokenize.cpp.s

.PHONY : tokenize.s

# target to generate assembly for a file
tokenize.cpp.s:
	$(MAKE) -f CMakeFiles/test_gui.dir/build.make CMakeFiles/test_gui.dir/tokenize.cpp.s
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/tokenize.cpp.s
	$(MAKE) -f CMakeFiles/sldraw.dir/build.make CMakeFiles/sldraw.dir/tokenize.cpp.s
	$(MAKE) -f CMakeFiles/slisp.dir/build.make CMakeFiles/slisp.dir/tokenize.cpp.s
.PHONY : tokenize.cpp.s

unittests.o: unittests.cpp.o

.PHONY : unittests.o

# target to build an object file
unittests.cpp.o:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/unittests.cpp.o
.PHONY : unittests.cpp.o

unittests.i: unittests.cpp.i

.PHONY : unittests.i

# target to preprocess a source file
unittests.cpp.i:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/unittests.cpp.i
.PHONY : unittests.cpp.i

unittests.s: unittests.cpp.s

.PHONY : unittests.s

# target to generate assembly for a file
unittests.cpp.s:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/unittests.cpp.s
.PHONY : unittests.cpp.s

unittests_autogen/mocs_compilation.o: unittests_autogen/mocs_compilation.cpp.o

.PHONY : unittests_autogen/mocs_compilation.o

# target to build an object file
unittests_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/unittests_autogen/mocs_compilation.cpp.o
.PHONY : unittests_autogen/mocs_compilation.cpp.o

unittests_autogen/mocs_compilation.i: unittests_autogen/mocs_compilation.cpp.i

.PHONY : unittests_autogen/mocs_compilation.i

# target to preprocess a source file
unittests_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/unittests_autogen/mocs_compilation.cpp.i
.PHONY : unittests_autogen/mocs_compilation.cpp.i

unittests_autogen/mocs_compilation.s: unittests_autogen/mocs_compilation.cpp.s

.PHONY : unittests_autogen/mocs_compilation.s

# target to generate assembly for a file
unittests_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/unittests_autogen/mocs_compilation.cpp.s
.PHONY : unittests_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... tidy"
	@echo "... test_message"
	@echo "... test_gui"
	@echo "... unittests"
	@echo "... sldraw"
	@echo "... coverage"
	@echo "... slisp"
	@echo "... test_message_autogen"
	@echo "... test_gui_autogen"
	@echo "... unittests_autogen"
	@echo "... sldraw_autogen"
	@echo "... slisp_autogen"
	@echo "... canvas_widget.o"
	@echo "... canvas_widget.i"
	@echo "... canvas_widget.s"
	@echo "... environment.o"
	@echo "... environment.i"
	@echo "... environment.s"
	@echo "... expression.o"
	@echo "... expression.i"
	@echo "... expression.s"
	@echo "... interpreter.o"
	@echo "... interpreter.i"
	@echo "... interpreter.s"
	@echo "... main_window.o"
	@echo "... main_window.i"
	@echo "... main_window.s"
	@echo "... message_widget.o"
	@echo "... message_widget.i"
	@echo "... message_widget.s"
	@echo "... qgraphics_arc_item.o"
	@echo "... qgraphics_arc_item.i"
	@echo "... qgraphics_arc_item.s"
	@echo "... qt_interpreter.o"
	@echo "... qt_interpreter.i"
	@echo "... qt_interpreter.s"
	@echo "... repl_widget.o"
	@echo "... repl_widget.i"
	@echo "... repl_widget.s"
	@echo "... sldraw.o"
	@echo "... sldraw.i"
	@echo "... sldraw.s"
	@echo "... sldraw_autogen/mocs_compilation.o"
	@echo "... sldraw_autogen/mocs_compilation.i"
	@echo "... sldraw_autogen/mocs_compilation.s"
	@echo "... slisp.o"
	@echo "... slisp.i"
	@echo "... slisp.s"
	@echo "... slisp_autogen/mocs_compilation.o"
	@echo "... slisp_autogen/mocs_compilation.i"
	@echo "... slisp_autogen/mocs_compilation.s"
	@echo "... test_gui.o"
	@echo "... test_gui.i"
	@echo "... test_gui.s"
	@echo "... test_gui_autogen/mocs_compilation.o"
	@echo "... test_gui_autogen/mocs_compilation.i"
	@echo "... test_gui_autogen/mocs_compilation.s"
	@echo "... test_interpreter.o"
	@echo "... test_interpreter.i"
	@echo "... test_interpreter.s"
	@echo "... test_message.o"
	@echo "... test_message.i"
	@echo "... test_message.s"
	@echo "... test_message_autogen/mocs_compilation.o"
	@echo "... test_message_autogen/mocs_compilation.i"
	@echo "... test_message_autogen/mocs_compilation.s"
	@echo "... test_tokenize.o"
	@echo "... test_tokenize.i"
	@echo "... test_tokenize.s"
	@echo "... test_types.o"
	@echo "... test_types.i"
	@echo "... test_types.s"
	@echo "... tokenize.o"
	@echo "... tokenize.i"
	@echo "... tokenize.s"
	@echo "... unittests.o"
	@echo "... unittests.i"
	@echo "... unittests.s"
	@echo "... unittests_autogen/mocs_compilation.o"
	@echo "... unittests_autogen/mocs_compilation.i"
	@echo "... unittests_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

