# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/yichenliu/Library/CloudStorage/OneDrive-VirginiaTech/ECE3574 NEW/ece3574-sp22-proj4-yichenl61"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/yichenliu/Library/CloudStorage/OneDrive-VirginiaTech/ECE3574 NEW/ece3574-sp22-proj4-yichenl61"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/Applications/CMake.app/Contents/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/yichenliu/Library/CloudStorage/OneDrive-VirginiaTech/ECE3574 NEW/ece3574-sp22-proj4-yichenl61/CMakeFiles" "/Users/yichenliu/Library/CloudStorage/OneDrive-VirginiaTech/ECE3574 NEW/ece3574-sp22-proj4-yichenl61//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/yichenliu/Library/CloudStorage/OneDrive-VirginiaTech/ECE3574 NEW/ece3574-sp22-proj4-yichenl61/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named unittests

# Build rule for target.
unittests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unittests
.PHONY : unittests

# fast build rule for target.
unittests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/build
.PHONY : unittests/fast

#=============================================================================
# Target rules for targets named cqbench

# Build rule for target.
cqbench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cqbench
.PHONY : cqbench

# fast build rule for target.
cqbench/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cqbench.dir/build.make CMakeFiles/cqbench.dir/build
.PHONY : cqbench/fast

cqbench.o: cqbench.cpp.o
.PHONY : cqbench.o

# target to build an object file
cqbench.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cqbench.dir/build.make CMakeFiles/cqbench.dir/cqbench.cpp.o
.PHONY : cqbench.cpp.o

cqbench.i: cqbench.cpp.i
.PHONY : cqbench.i

# target to preprocess a source file
cqbench.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cqbench.dir/build.make CMakeFiles/cqbench.dir/cqbench.cpp.i
.PHONY : cqbench.cpp.i

cqbench.s: cqbench.cpp.s
.PHONY : cqbench.s

# target to generate assembly for a file
cqbench.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cqbench.dir/build.make CMakeFiles/cqbench.dir/cqbench.cpp.s
.PHONY : cqbench.cpp.s

test_cqsort.o: test_cqsort.cpp.o
.PHONY : test_cqsort.o

# target to build an object file
test_cqsort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/test_cqsort.cpp.o
.PHONY : test_cqsort.cpp.o

test_cqsort.i: test_cqsort.cpp.i
.PHONY : test_cqsort.i

# target to preprocess a source file
test_cqsort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/test_cqsort.cpp.i
.PHONY : test_cqsort.cpp.i

test_cqsort.s: test_cqsort.cpp.s
.PHONY : test_cqsort.s

# target to generate assembly for a file
test_cqsort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/test_cqsort.cpp.s
.PHONY : test_cqsort.cpp.s

unittests.o: unittests.cpp.o
.PHONY : unittests.o

# target to build an object file
unittests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/unittests.cpp.o
.PHONY : unittests.cpp.o

unittests.i: unittests.cpp.i
.PHONY : unittests.i

# target to preprocess a source file
unittests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/unittests.cpp.i
.PHONY : unittests.cpp.i

unittests.s: unittests.cpp.s
.PHONY : unittests.s

# target to generate assembly for a file
unittests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/unittests.cpp.s
.PHONY : unittests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... cqbench"
	@echo "... unittests"
	@echo "... cqbench.o"
	@echo "... cqbench.i"
	@echo "... cqbench.s"
	@echo "... test_cqsort.o"
	@echo "... test_cqsort.i"
	@echo "... test_cqsort.s"
	@echo "... unittests.o"
	@echo "... unittests.i"
	@echo "... unittests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

